name: riskylobster
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37h1ba5d50_0
  - inflection=0.3.1=py37_1
  - intel-openmp=2019.4=243
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - more-itertools=7.2.0=py37_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - openssl=1.1.1c=h7b6447c_1
  - pandas=0.25.0=py37he6710b0_0
  - pip=19.2.2=py37_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.0=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - python-decouple=3.1=py_0
  - pytz=2019.2=py_0
  - quandl=3.4.5=py37_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alpha-vantage==2.1.0
    - datetime==4.3
    - idna==2.8
    - intrinio-sdk==4.0.0
    - six==1.12.0
    - urllib3==1.25.3
    - zope-interface==4.6.0

